import './globals.css'
import { Inter } from 'next/font/google'
import { StateContext } from '@/context/StateContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DashBoard_Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
        {children}
        </StateContext>
        </body>
    </html>
  )
}
